# Render configuration
version: "1"

services:
  - type: web
    name: codebud-dsa-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    rootDir: server
    envVars:
      - key: PORT
        value: 5001
      - key: PYTHONPATH
        value: /opt/render/project/src
